### ISSUE TITLE
Homepage UI and contents update

### ISSUE THREAD

**Issue by vivekpathakgit** [hacktoberfest-codex/Namami-Gange-Guide#39]

**Comment by dipanshu-m** [comment]
pay extra attention to images and their placement

**Comment by vivekpathakgit** [comment]
![image](https://github.com/hacktoberfest-codex/Namami-Gange-Guide/assets/93838914/32de3b7f-0cf2-4446-9b76-23827b3ebc6a)
A description section and cursor is set to pointer when hovered on image.
